### ISSUE TITLE
Is go to definition working?

### ISSUE THREAD

**Issue by ggilmore** [mtsmfm/vscode-ruby-lsc#4]
I downloaded the latest version of the extension (`0.1.1` at this time), and tried to use it on the https://github.com/mtsmfm/language_server-ruby project itself. 

I tried to go to definition with `result` on [line 70 in this file](https://github.com/mtsmfm/language_server-ruby/blob/3ee613da8977afedd5529b5db91487326436ad43/lib/language_server/project.rb#L70). I expected it to take me to [the declaration right above it](https://github.com/mtsmfm/language_server-ruby/blob/3ee613da8977afedd5529b5db91487326436ad43/lib/language_server/project.rb#L68), but instead it says that no definition was found. 

Is this expected to work? I haven't modified any of the default options for the extension.

**Comment by mtsmfm** [comment]
Thank you for your trying.
Currently, go to difinition is experimental feature so you must specify `--experimental-features` flag

https://github.com/mtsmfm/language_server-ruby/blob/3ee613da8977afedd5529b5db91487326436ad43/exe/language_server-ruby#L14

**Comment by ggilmore** [comment]
Thanks for the quick reply! Unfortunately, repeating the same steps above causes me to experience the issue described in https://github.com/mtsmfm/language_server-ruby/issues/36. I'll close this issue in favor of that one.
